### ISSUE TITLE
How to do prediction?

### ISSUE THREAD

**Issue by nikivazou** [andrewdougherty/svm#1]
Hi @andrewdougherty,

I can see how you provide the code to train the predictor, but then how do you use the svm to actually make the prediction?

Thanks, 
Niki

**Comment by andrewdougherty** [comment]
Hi @nikivazou,

Sorry it took me so long to respond. There is a simulate function in the SVM class that lets you use an existing SVM solution on new sets of points. Create the SVM, run the solution on the test points and then feed the new points into the simulate function.

Andrew

**Comment by nikivazou** [comment]
Great, thanks Andrew!
